### ISSUE TITLE
Production code for styling

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#224]
Tracking the following things for production styling:

- [x] Update heading styling in patterns (#277)
- [x] Update link styling  (#277)
- [x] Header Styling  (#277)
- [x] Subnav Styling  (#277)
- [x] Resource Panel Styling (#289)
- [x] Bottom Nav Styling (https://github.com/IBM-Watson/design-library/issues/225#issuecomment-99119475, https://github.com/IBM-Watson/design-library/issues/221) (#277)
- [x] Footer Styling (#279)
- [x] Site Layout  (#277)
- [x] Aside Subcontent Styling (#303)
- [x] Color Subcontent Styling (#303)
- [x] Detail Subcontent Styling (#303)
- [x] Example Subcontent Styling (#303)
- [x] Quote Subcontent Styling  (#277)
- [x] Homepage Styling (#301)
- [x] 404 Styling (if needed)
- [ ] Pattern List Styling (#320)

**Comment by Snugug** [comment]
Final bit resolved by #301

**Comment by Snugug** [comment]
Pattern list styling still needs to be done
