### ISSUE TITLE
Launch Defects

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#322]
The following defects are blockers for launch on the 19th. Goal is to have these resolved by by 2pm Eastern on the 19th. `( )` are PRs to resolve, `[ ]` are related issues.

- [x] Resource link underline askew when they wrap (#323)
- [x] Too many JavaScript requests (#324)
- [x] Correctly render patterns (#338) [#294]
- [x] Update Label pattern (#328) [#292]
- [x] Update patterns to align with guidelines (#338) [#267]
- [x] Autoplay Animation video examples (#332) [#326]
- [x] All Example descriptions should visually be captions (#327) [#325] 
- [x] Update Rhythm (#359) [#330]
- [x] Loading Indicator Doesn't Minimize Cleanly (#337) [#333]
- [ ] Image styling issues on Wordmark and Logo page [#339]
- [x] Citation on blockquote shouldn't be italicized (#338) [#335]
